### PR TITLE
Closes #31: Add a check if page is scrolled down.

### LINKED ISSUE #31: Wrong OCI picked up if scroll happens before beacon fires - Beacon side
**Describe the bug**
Wrong OCI will be picked up if the page is scrolled and the beacon script is fired after. 
This issue will handle the `rocket-scripts` side. 

## Reproduce the problem

- Use - https://gist.github.com/DahmaniAdame/bd58d4be051f5995aa2318d341eb342a
- Scroll to the last image
- Hit refresh while making sure the beacon runs
- See the LCP image will be related to the current viewport

## Identify the root cause
The issue is that the OCI data is collected incorrectly if the user scrolls before the beacon fires. This can happen when the user scrolls on mobile or refreshes the page away from the fold.

## Scope a solution
To solve the issue, we must create a new function in [BeaconManager.js](https://github.com/wp-media/rocket-scripts/blob/8e25bbfddce70e1c142bb879f9467061f6696dd7/src/BeaconManager.js):
``` javascript
  _isPageScrolled() {
        return window.pageYOffset > 0 || document.documentElement.scrollTop > 0;
    }
```
and finalize the process of beacon if it returns `true`:
``` javascript
    async init() {
        this.scriptTimer = new Date();
        if (!await this._isValidPreconditions()) {
            this._finalize();
            return;
        }

        if (this._isPageScrolled()) {
            this.logger.logMessage('Bailing out because the page has been scrolled');
            this._finalize();
            return;
        }
// ...
```

## Development steps:
- [ ] Create the function `_isPageScrolled()`
- [ ] Modify `init` function to finalize if the newly added function returns true.

## Effort estimation: 
XS

## Is a refactor needed in that part of the codebase?
No

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #31 
This PR adds a check to ensure that the beacon is not fired if the page is scrolled down before it runs. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario

- Use - https://gist.github.com/DahmaniAdame/bd58d4be051f5995aa2318d341eb342a
- Scroll to the last image
- Hit refresh while making sure the beacon runs
- See the LCP image will be related to the current viewport

### Documentation

The `_isPageScrolled()` method is used in `BeaconManager.js` to check if the page is scrolled and bails out if it returns true. In-build test have been added as well.

### New dependencies

None

### Risks

None

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.
- [x] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [x] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Review by Khadreal — DISMISSED** [review]

File: src/BeaconManager.js [hunk 1]
```diff
@@ -143,6 +149,10 @@ class BeaconManager {
         this._saveFinalResultIntoDB();
     }
 
+    _isPageScrolled() {
+        return window.pageYOffset > 0 || document.documentElement.scrollTop > 0;
+    }
```
Comment (wordpressfan) [inline src/BeaconManager.js]: This should be an `Util` method so it can be used anywhere

**Review by wordpressfan — CHANGES_REQUESTED** [review]
I think @Miraeld is not working today, I'll go ahead and do that small change by myself.

**Review by Khadreal — APPROVED** [review]

**Review by wordpressfan — APPROVED** [review]
