### PR TITLE
Closes #49: otf and eot fonts shouldn't be processed by default with preload fonts

### LINKED ISSUE #49: otf and eot fonts shouldn't be processed by default with preload fonts
**Describe the bug**
When access a page with otf/eot fonta and preload fonts is enabled, only woff, woff2 and ttf should be processed by default, however , currently otf /eot will be processed as well

**To Reproduce**
1. install and activate 3.19
2. enable preload fonts
3. access page with different fonts
4. clear cache 
5. revisit the page and check HTML => otf is preloaded

**Expected behavior**
only woff, woff2, ttf are preloaded by default unless filter is used to enable other extensions too

**Additional context**
- slack https://group-onecom.slack.com/archives/C08EFCYRQ2X/p1746772695954649

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #49
The list of font extensions processed will now be dynamically coming from WP Rocket filter rather than a static value.

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

### What was tested

The value is coming from the variable in the page. If we can't get it, then we have default values.

### How to test

Please run with https://github.com/wp-media/wp-rocket/pull/7318 to have the actual variable being added to the html

### Documentation

This pull request updates the `BeaconPreloadFonts` class to allow configurable font file extensions and improves the flexibility of font file detection. The most important changes include replacing the static `FONT_FILE_REGEX` with an instance-specific regex based on the configuration and updating font-loading logic to use the new regex.

### Updates to font file detection:

* [`src/BeaconPreloadFonts.js`](diffhunk://#diff-2604b2fd59254542b65254d68b26f17a1ccae4873a61e4e2392edc00a043d013R7-L10): Replaced the static `FONT_FILE_REGEX` with an instance-specific regex (`this.FONT_FILE_REGEX`) that is dynamically generated based on the `processed_extensions` configuration. If no configuration is provided, it defaults to `["woff", "woff2", "ttf"]`. This change ensures greater flexibility in specifying font file extensions.

* [`src/BeaconPreloadFonts.js`](diffhunk://#diff-2604b2fd59254542b65254d68b26f17a1ccae4873a61e4e2392edc00a043d013L78-R84): Updated the `getNetworkLoadedFonts` method to use the instance-specific `this.FONT_FILE_REGEX` instead of the removed static `FONT_FILE_REGEX`. This aligns the method with the new customizable regex logic.
### New dependencies

None
### Risks

None
# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification
No test for that

### CODE REVIEW

File: src/BeaconPreloadFonts.js [hunk 1]
```diff
@@ -4,10 +4,15 @@ class BeaconPreloadFonts {
         this.config = config;
         this.logger = logger;
         this.aboveTheFoldFonts = [];
+        // Use processed_extensions from config if set, otherwise default to ["woff", "woff2", "ttf"].
+        const extensions = (Array.isArray(this.config.processed_extensions) && this.config.processed_extensions.length > 0
+            ? this.config.processed_extensions
+            : ["woff", "woff2", "ttf"])
```
Comment (jeawhanlee) [inline src/BeaconPreloadFonts.js:10]: What do you think about making this default logic on PHP side, so we have a single continuous logic on PHP alone and we just need to pass down the data to even take a step further maybe even construct the regex over at php and we just handle only data here, no logic.

Comment (wordpressfan) [reply src/BeaconPreloadFonts.js:10]: I think this is what exactly happens here, no?
I think those extensions are fallback only.

Comment (jeawhanlee) [reply src/BeaconPreloadFonts.js:10]: Yes, but moving it to PHP by checking if filtered result is empty and return the default there instead of on the js.

Comment (jeawhanlee) [reply src/BeaconPreloadFonts.js:10]: It's a cosmetic enhancement anyway, if you don't see the need for it, then we don't need to.

Comment (Miraeld) [reply src/BeaconPreloadFonts.js:10]: I put this in JS as well, in case, we never know why, the variable doesn't exist, even tho it should be impossible to happen. Instead of having an error that stops everything, in this incredible edge case, we would at least process something.

Comment (jeawhanlee) [reply src/BeaconPreloadFonts.js:10]: Ok, then, let's leave it.

**Review by jeawhanlee — APPROVED** [review]

**Comment by jeawhanlee** [comment]
@Miraeld Can we include the changes here in this [PR](https://github.com/wp-media/wp-rocket/pull/7318) following [these](https://github.com/wp-media/rocket-scripts?tab=readme-ov-file#updating-wp-rocket) steps

**Comment by Miraeld** [comment]
@jeawhanlee Done :)
